**Name :Suraj Sanjeev Pawar**

**Registration ID :GO-WTP-1839**

**Task-5 : Prediction using Supervised Machine Learning using Logistic Regression**

***In this task we have To identify different species  (setosa, versicolor, verginica) of Iris flowers given just 4 features: their sepal and petal lengths and widths.
The name multinomial logistic regression is usually reserved for the case when the dependent variable has three or more unique values, such as Married, Single, Divored, or Widowed. 
Used to solve classification problem
The response variable categorical in nature.
It helps to calculate the of possibility a particular event taking place.***


***Logistic regression and iris flowers classification  problem
Logistic regression is a statistical method for analyzing a dataset in which there are one or more independent variables that determine an outcome.
The name logistic regression is used when the dependent variable has only two values, such as 0 and 1 or Yes and No.***

***To identify different species  (setosa, versicolor, verginica) of Iris flowers given just 4 features: their sepal and petal lengths and widths.
There are 50 observation for each species, total - 150.***

***This problem can be solved by using Regression libraries and task is given by Goeduhub Technologies as Online Winter training in Machine Learning using Python.***

***Importing required libraries***

In [ ]:
#implementation of logistic regression
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LogisticRegression

***Import Dataset refer from scikit-Learn(inbuild)*** 

In [ ]:
#import dataset
from sklearn.datasets import load_iris
iris=load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

***iris Data-set is a dictionary data set let's see keys of dictionary***

In [ ]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

***target species***  

In [ ]:
print(iris.target_names) #three types of flowers we have

['setosa' 'versicolor' 'virginica']


***Features Name***

In [ ]:
print(iris.feature_names) #we have four features

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


***Initializing DataFrame***

In [ ]:
#convert dataset into DataFrame
df=pd.DataFrame(iris.data)
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

***Adding features_name as column in DataFrame*** 

In [ ]:
#put name of the feature as column header
df.columns=iris.feature_names
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

***Data Information for preprocessing of Data***

In [ ]:
#Information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


***Defining X and Y  (Dependent and independent variables )***

In [ ]:
#divide our data into dependent and independent variable
X=iris.data     #independent variable
Y=iris.target   #dependent variable
print(X.shape)   #150 rows and 4 columns
print(Y.shape)   #only 150 rows

(150, 4)
(150,)


***Splitting Train and test Data***

In [ ]:
#splitting train and test data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=1)

***Scaling Data***

In [ ]:
#Scaling of data
#StandardScaler scaling of the features as X
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train) #
X_test=sc.transform(X_test)       #


In [ ]:
X_test

array([[-0.03642412,  2.33486893, -1.46412347, -1.31014421],
       [-0.8763215 , -1.25723711, -0.44840671, -0.14041404],
       [ 0.92345859, -0.05986843,  0.34159522,  0.24949602],
       [-0.51636548,  2.09539519, -1.40769476, -1.05020417],
       [ 2.48326801,  1.85592145,  1.47016941,  1.02931613],
       [ 0.56350258,  0.65855277,  0.51088135,  0.50943606],
       [ 1.28341461,  0.1796053 ,  0.73659619,  1.41922619],
       [-0.8763215 ,  1.85592145, -1.06912251, -1.05020417],
       [-1.35626285,  0.41907904, -1.23840864, -1.31014421],
       [ 1.28341461,  0.41907904,  1.07516844,  1.41922619],
       [-0.2763948 , -0.77828964,  0.2287378 ,  0.119526  ],
       [-0.51636548,  2.09539519, -1.18197993, -1.05020417],
       [ 1.52338529, -0.05986843,  1.18802586,  1.15928615],
       [ 0.68348792,  0.41907904,  0.39802393,  0.37946604],
       [ 0.20354656, -0.29934217,  0.39802393,  0.37946604],
       [-1.71621887,  0.41907904, -1.40769476, -1.31014421],
       [-0.03642412, -1.

***Import logisticRegression and Training of the model***

In [ ]:
model=LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

***Evaluation of model / Prediction of test Data***

In [ ]:
#prediction of test data
Y_pred=model.predict(X_test)
print(Y_pred)

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0]


***Confusion_ matrix  is used calculate to  accuracy of the model***

In [ ]:
#Calculate Confusion Matrix correct predictions as diagonals
#Based on Categorical data
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

***Calculating Accuracy  accuracy score function*** 

In [ ]:
#Calculate the Accuracy Score
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_pred))

0.9736842105263158


***Import LabelEncoder***

In [ ]:
#import LabelEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
#example refer form scikit-learn
le.fit(["paris", "paris", "tokyo", "amsterdam"]) #pass a columns names
list(le.classes_)   #get only unique values


['amsterdam', 'paris', 'tokyo']

In [ ]:
le.transform(["tokyo", "tokyo", "paris"])

array([2, 2, 1])

In [ ]:
list(le.inverse_transform([2, 2, 1]))

['tokyo', 'tokyo', 'paris']

***Import OneHotEncoder***

In [ ]:
#import OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
#example refer form scikit-learn
enc = OneHotEncoder(handle_unknown='ignore')
Z = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(Z)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='ignore', sparse=True)

In [ ]:
enc.categories_

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]

In [ ]:
enc.transform([['Female', 1], ['Male', 4]]).toarray()

array([[1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [ ]:
enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])

array([['Male', 1],
       [None, 2]], dtype=object)

In [ ]:
enc.get_feature_names(['gender', 'group'])

array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'],
      dtype=object)

***Thank you Goeduhub Techonologies***